version: "3.5"

services:
  web:
    container_name: dockerdev
    build: ./
    ports:
      - "3000:3000"
    # environment:
      # DD_DB_HOST: db
    command: /server
    # depends_on:
    #   - db
  # db:
  #   container_name: dockerdev-db
  #   image: postgres:12.2-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: goland
  #     POSTGRES_PASSWORD: goland
  #     POSTGRES_DB: goland
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql